### ISSUE TITLE
Can not compile the source code

### ISSUE THREAD

**Issue by gitnewcomer** [invizbox/invizbox-2#1]
Hi, I am always getting errors trying to compile the source code for the Invizbox 2. It seems that it needs the Luci source code, but if I add the source from OpenWRT it gives more errors with Luci. Can you give me some hints what I can do? Thank you.

**Comment by invizbox** [comment]
Hi,
if you are referring to the warnings at the beginning when the feeds are getting set up, these are just warnings.
There is no dependency from Luci in the InvizBox 2 project as we have our own Administration Interface (admin-interface package). These dependencies are there for the InvizBox original and Go builds.
I don't expect these would prevent you from building the project. Can you look further down for errors? If you have reached the stage where tools and packages are being built, you can run make with the usual OpenWRT debug flags in the "openwrt" folder.
Vincent

**Comment by invizbox** [comment]
Just noticed that your issue was 20 days old, there were a couple of things fixed in the release for 0.1.3. I had lost a Makefile for the admin-interface package when putting together the 0.0.41 build. This should be fixed now. Let me know how the new release builds for you.

**Comment by gitnewcomer** [comment]
Hi, sorry for my late reply. Yes, with the new release it still shows the warnings but builds the firmware. Thanks for the support!
